### PR TITLE
Make it run on Ubuntu 14.04, closes #9

### LINKED ISSUE #9: *555# does not work, ValueError: invalid literal for int() with base 10: ''
`*555#` is not documented yet but i gather that it should show Wikipedia.

```
DOSBox version 0.74
Copyright 2002-2010 DOSBox Team, published under GNU GPL.
---
CONFIG:Loading primary settings from config file dosbox.conf
Neu-Ulm running.
MIXER:Got different values from SDL: freq 44100, blocksize 512
ALSA:Can't subscribe to MIDI port (65:0) nor (17:0)
MIDI:Opened device:none
Serial3: Opening ../tmp/ttyV0
Modem command: 'AT&F'
Modem command: 'ATX3DP01910'
showing page: '00000a'
compressed 497 down to 323
Sending pal/char: .OK
Sending text: .....................................OK
history: ['00000a']
links: {}
In: 0x1c
In: 0x1c
In: 0x1c
login ok
input_data: {'$command': '000001a'}
showing page: '000001a'
messages file not found
messages file not found
loading: '../data/00000/a.inc'
Sending pal/char: .........OK
Sending text: ........................................OK
history: ['00000a', '000001a']
links: {'#': '0', '7': '77'}
In: 0x1c
input_data: {'$navigation': ''}
Cept.tershowing page: '0a'
filename: 'a'
loading: '../data/0/a.inc'
Sending pal/char: .........OK
Sending text: ....................................OK
history: ['00000a', '000001a', '0a']
links: {'6': '10401131', '7': '78', '8': '8', '9': '9'}
In: 0x13
entering command mode
In: 0x35
self.__data:
['\x135                  ']
self.string:
'\x135'
In: 0x35
self.__data:
['\x1355                 ']
self.string:
'\x1355'
In: 0x35
self.__data:
['\x13555                ']
self.string:
'\x13555'
In: 0x1c
exited command mode
'<INI>555'
input_data: {'$command': '555'}
showing page: '555a'
Traceback (most recent call last):
  File "neu-ulm.py", line 603, in <module>
    ret = create_page(desired_pageid)
  File "neu-ulm.py", line 249, in create_page
    ret = Wikipedia_UI.create_page(pageid)
  File "/home/me/squashfs-root/usr/server/wikipedia.py", line 421, in create_page
    return Wikipedia_UI.create_wiki_page(int(pageid[3:-1]), ord(pageid[-1]) - ord("a"))
ValueError: invalid literal for int() with base 10: ''
2019/01/15 22:12:35 socat[22691] W waitpid(): child 22693 exited with status 1
2019/01/15 22:12:35 socat[22691] N socket 1 (fd 3) is at EOF
2019/01/15 22:12:36 socat[22691] N exiting with status 0
```

### PR DESCRIPTION
**Pull request by probonopd**
Closes https://github.com/bildschirmtext/bildschirmtext/issues/9#issuecomment-455603790

### CODE REVIEW

**Comment by mist64** [comment]
There is no good answer for this yet. I test everything with an actual MultiTel-D terminal, but it only displays black and white. In terms of hardware, the C64 Decoder Cartridge would be great, but it requires an adapter because it wants to see a DBT-03 modem.

For software decoders, all MS-DOS based ones won't be able to display the correct pixels, because VGA can't do the resolution (unless there's a SuperVGA one?). The Amiga decoder should display everything right, but I haven't succeeded in connecting FS-UAE to an emulated serial port. Windows decoders including the original T-Online software should be good too (if you run Windows with at least 256 colors), but I haven't had much luck with these decoders yet either. :(

**Comment by probonopd** [comment]
So basically you are saying that to get a MultiTel quality decoder on modern-day Linux we'd have to write one? Or are you aware of ancient open source ones for Linux which could be resurrected?

**Comment by mist64** [comment]
I still have faith in the Amiga decoder. For someone who knows what they are doing, it should be easy to set up an emulator or even AROS. I was also recently given a collection of 5 Windows-based decoders (I'll ask whether I can share them), any of which could be exactly what we are looking for, and since they are all 16 bit and from ~1991-1995, Wine should be able to support them.

If we wanted to write our own decoder, we could start out with a Videotext (the television vblank data one) decoder and extend the higher-level CEPT features. Someone told me that there was actually a later Videotext standard (that was rarely used) that mostly matched Bildschirmtext CEPT, and that some open source Videotext decoder supported this. Investigation needed.

If we wanted to write our own decoder, it wouldn't be too complicated. The architecture is pretty simple: There is a 40x24 text buffer with about 32 bits per character, which contains ~10 bits for the character index, 5 bits for the foreground color, 5 bits for the background color, one bit each for hsize, vsize, marked, hidden, two or so bits for blinking. The incoming screen gets decoded and converted into these 32 bit entries in screen RAM, and the video chip interprets these 32 bit values as it is refreshing the screen. It's architected very much after 8 bit computers from the early 80s.

I can imagine it would be fun writing such a decoder. :)

**Comment by probonopd** [comment]
Thanks for merging. I will see if I can get https://github.com/probonopd/XCept to build.

**Comment by probonopd** [comment]
Thanks for merging. See what I found: https://github.com/probonopd/XCept

Unfortunately I could not get it to build (help welcome).

**Pull request merged**
